name: emergency_services_app
description: A Flutter application for finding and contacting emergency services.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  provider: ^6.0.5
  http: ^1.1.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.1.12
  google_maps_flutter: ^2.3.0
  flutter_polyline_points: ^2.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.8.4
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1
  logger: ^2.0.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - .env
